# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PV3URJSUVe3vtw0O7ZOH55jfJtdWDJ2v
"""

!pip install streamlit

# streamlit_app.py
import streamlit as st
import pickle

# Load model and vectorizer
model = pickle.load(open('model.pkl', 'rb'))
vectorizer = pickle.load(open('vectorizer.pkl', 'rb'))

st.set_page_config(page_title="Spam vs Ham Classifier")
st.title("📨 Spam vs Ham Email Classifier")
st.write("Enter an email or message to classify it as spam or ham.")

# User input
user_input = st.text_area("Your message here:")

if st.button("Classify"):
    if user_input.strip() == "":
        st.warning("Please enter a message.")
    else:
        transformed = vectorizer.transform([user_input])
        prediction = model.predict(transformed)[0]
        st.success(f"🧠 Prediction: **{'Spam' if prediction == 'spam' else 'Ham'}**")